FROM maven:3.9-eclipse-temurin-21 AS build

WORKDIR /build

COPY . .

RUN mvn -q -DskipTests package

FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /build/eureka-server/target/eureka-server-*-exec.jar app.jar

EXPOSE 8761

ENTRYPOINT ["java", "-jar", "app.jar"]