spring:
  application:
    name: eureka-server

server:
  port: ${PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URL:https://git-insight-eureka.onrender.com/eureka/}

  server:
    enable-self-preservation: true