spring:
  application:
    name: analytics-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    open-in-view: false

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration


server:
  port: ${PORT:8082}


eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: ${EUREKA_URL:https://git-insight-eureka.onrender.com/eureka/}

  instance:
    prefer-ip-address: false
    hostname: ${RENDER_EXTERNAL_HOSTNAME:localhost}